sudo: false

language: node_js
node_js:
  - 6
  - 9

branches:
  only:
    - test_travis

script:
  - npm run lint

deploy:
  provider: heroku
  app: react-redux-router
  api_key:
    secure: 444198ff-70c7-44a9-80b2-0adfe414753f
